name: Run Streamlit App

on:
  push:
    branches:
      - main  # Executa quando há push na branch main
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Escolha a versão do Python necessária

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
        pip install -r requirements.txt  # Certifique-se de ter o arquivo requirements.txt no seu repositório

    - name: Run Streamlit
      run: |
        streamlit run ./areaenel.py
